name: beacon_client
description: An abstraction over the BeaconCRM API
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
